# Generated by Django 2.0.7 on 2019-01-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_article_recommendations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='recommendations',
        ),
        migrations.AddField(
            model_name='article',
            name='email',
            field=models.EmailField(default=True, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
