# Generated by Django 2.0.7 on 2019-01-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190114_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
